package builder

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/artmsilva/cssmark/src/internal/parser"
)

// WriteCSS writes tokens to a clean CSS file with :root variables
func WriteCSS(tokens []parser.Token, path string) error {
	return WriteCSSWithModeSelectors(tokens, path, nil)
}

// WriteCSSWithModeSelectors writes CSS with optional per-mode selector overrides.
func WriteCSSWithModeSelectors(tokens []parser.Token, path string, modeSelectors map[string]string) error {
	return os.WriteFile(path, []byte(ToCSSWithModeSelectors(tokens, modeSelectors)), 0644)
}

// ToCSS converts tokens to a clean CSS string with :root variables.
func ToCSS(tokens []parser.Token) string {
	return ToCSSWithModeSelectors(tokens, nil)
}

// ToCSSWithModeSelectors emits a configured selector for a mode when supplied.
func ToCSSWithModeSelectors(tokens []parser.Token, modeSelectors map[string]string) string {
	tokens = append(tokens, typographyShorthands(tokens)...)
	var sb strings.Builder

	sb.WriteString("/* Generated by cssmark - https://github.com/artmsilva/cssmark */\n\n")

	// Group tokens by category
	categories := make(map[string][]parser.Token)
	var categoryOrder []string

	for _, t := range tokens {
		cat := t.Category
		if cat == "" {
			cat = "uncategorized"
		}
		if _, exists := categories[cat]; !exists {
			categoryOrder = append(categoryOrder, cat)
		}
		categories[cat] = append(categories[cat], t)
	}

	// Sort categories
	sort.Strings(categoryOrder)

	sb.WriteString(":root {\n")

	for i, cat := range categoryOrder {
		if i > 0 {
			sb.WriteString("\n")
		}

		// Write category comment
		sb.WriteString(fmt.Sprintf("  /* %s */\n", sanitizeCSSComment(cat)))

		// Sort tokens within category by name
		catTokens := categories[cat]
		sort.Slice(catTokens, func(i, j int) bool {
			return catTokens[i].Name < catTokens[j].Name
		})

		for _, t := range catTokens {
			// Use the original var() reference if available, resolved literal otherwise
			value := t.InitialValue
			if t.RawInitialValue != "" {
				value = t.RawInitialValue
			}

			if t.Deprecated {
				sb.WriteString(fmt.Sprintf("  /* @deprecated */ %s: %s;\n", t.Name, value))
			} else {
				sb.WriteString(fmt.Sprintf("  %s: %s;\n", t.Name, value))
			}
		}
	}

	sb.WriteString("}\n")

	// Collect mode overrides across all tokens
	modeTokens := make(map[string][]parser.Token) // modeName → tokens with that mode
	var modeOrder []string

	for _, t := range tokens {
		for modeName := range t.Modes {
			if _, exists := modeTokens[modeName]; !exists {
				modeOrder = append(modeOrder, modeName)
			}
			modeTokens[modeName] = append(modeTokens[modeName], t)
		}
	}

	sort.Strings(modeOrder)

	for _, modeName := range modeOrder {
		selector := fmt.Sprintf(":root[data-color-mode='%s']", modeName)
		if configured, ok := modeSelectors[modeName]; ok && configured != "" {
			selector = configured
		}
		sb.WriteString(fmt.Sprintf("\n%s {\n", selector))

		mTokens := modeTokens[modeName]
		sort.Slice(mTokens, func(i, j int) bool {
			return mTokens[i].Name < mTokens[j].Name
		})

		for _, t := range mTokens {
			// Use the original var() reference if available
			value := t.Modes[modeName]
			if raw, exists := t.RawModes[modeName]; exists {
				value = raw
			}
			sb.WriteString(fmt.Sprintf("  %s: %s;\n", t.Name, value))
		}

		sb.WriteString("}\n")
	}

	return sb.String()
}

// typographyShorthands rebuilds a legacy font shorthand from the five scalar
// axes. The shorthand references the axes, so a mode only needs to override
// the axis that changes.
func typographyShorthands(tokens []parser.Token) []parser.Token {
	type group struct {
		base, category string
		axes           map[string]string
	}
	groups := map[string]*group{}
	for _, token := range tokens {
		if token.Composite == "" {
			continue
		}
		for _, axis := range []string{"font-family", "font-size", "font-style", "font-weight", "line-height"} {
			if !strings.HasSuffix(token.Name, "-"+axis) {
				continue
			}
			g := groups[token.Composite]
			if g == nil {
				g = &group{base: strings.TrimSuffix(token.Name, "-"+axis), category: token.Category, axes: map[string]string{}}
				groups[token.Composite] = g
			}
			g.axes[axis] = token.Name
		}
	}
	var result []parser.Token
	for _, group := range groups {
		if len(group.axes) != 5 {
			continue
		}
		result = append(result, parser.Token{
			Name: group.base, Category: group.category,
			InitialValue: fmt.Sprintf("var(%s) var(%s) var(%s)/var(%s) var(%s)", group.axes["font-style"], group.axes["font-weight"], group.axes["font-size"], group.axes["line-height"], group.axes["font-family"]),
		})
	}
	return result
}
