package builder

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/artmsilva/cssmark/src/internal/parser"
)

// WriteCSS writes tokens to a clean CSS file with :root variables
func WriteCSS(tokens []parser.Token, path string) error {
	css := ToCSS(tokens)
	return os.WriteFile(path, []byte(css), 0644)
}

// ToCSS converts tokens to a clean CSS string with :root variables
func ToCSS(tokens []parser.Token) string {
	var sb strings.Builder

	sb.WriteString("/* Generated by cssmark - https://github.com/artmsilva/cssmark */\n\n")

	// Group tokens by category
	categories := make(map[string][]parser.Token)
	var categoryOrder []string

	for _, t := range tokens {
		cat := t.Category
		if cat == "" {
			cat = "uncategorized"
		}
		if _, exists := categories[cat]; !exists {
			categoryOrder = append(categoryOrder, cat)
		}
		categories[cat] = append(categories[cat], t)
	}

	// Sort categories
	sort.Strings(categoryOrder)

	sb.WriteString(":root {\n")

	for i, cat := range categoryOrder {
		if i > 0 {
			sb.WriteString("\n")
		}

		// Write category comment
		sb.WriteString(fmt.Sprintf("  /* %s */\n", cat))

		// Sort tokens within category by name
		catTokens := categories[cat]
		sort.Slice(catTokens, func(i, j int) bool {
			return catTokens[i].Name < catTokens[j].Name
		})

		for _, t := range catTokens {
			if t.Deprecated {
				sb.WriteString(fmt.Sprintf("  /* @deprecated */ %s: %s;\n", t.Name, t.InitialValue))
			} else {
				sb.WriteString(fmt.Sprintf("  %s: %s;\n", t.Name, t.InitialValue))
			}
		}
	}

	sb.WriteString("}\n")

	return sb.String()
}
