package builder

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/artmsilva/cssmark/src/internal/parser"
)

// WriteCSS writes tokens to a clean CSS file with :root variables
func WriteCSS(tokens []parser.Token, path string) error {
	css := ToCSS(tokens)
	return os.WriteFile(path, []byte(css), 0644)
}

// ToCSS converts tokens to a clean CSS string with :root variables
func ToCSS(tokens []parser.Token) string {
	var sb strings.Builder

	sb.WriteString("/* Generated by cssmark - https://github.com/artmsilva/cssmark */\n\n")

	// Group tokens by category
	categories := make(map[string][]parser.Token)
	var categoryOrder []string

	for _, t := range tokens {
		cat := t.Category
		if cat == "" {
			cat = "uncategorized"
		}
		if _, exists := categories[cat]; !exists {
			categoryOrder = append(categoryOrder, cat)
		}
		categories[cat] = append(categories[cat], t)
	}

	// Sort categories
	sort.Strings(categoryOrder)

	sb.WriteString(":root {\n")

	for i, cat := range categoryOrder {
		if i > 0 {
			sb.WriteString("\n")
		}

		// Write category comment
		sb.WriteString(fmt.Sprintf("  /* %s */\n", cat))

		// Sort tokens within category by name
		catTokens := categories[cat]
		sort.Slice(catTokens, func(i, j int) bool {
			return catTokens[i].Name < catTokens[j].Name
		})

		for _, t := range catTokens {
			// Use the original var() reference if available, resolved literal otherwise
			value := t.InitialValue
			if t.RawInitialValue != "" {
				value = t.RawInitialValue
			}

			if t.Deprecated {
				sb.WriteString(fmt.Sprintf("  /* @deprecated */ %s: %s;\n", t.Name, value))
			} else {
				sb.WriteString(fmt.Sprintf("  %s: %s;\n", t.Name, value))
			}
		}
	}

	sb.WriteString("}\n")

	// Collect mode overrides across all tokens
	modeTokens := make(map[string][]parser.Token) // modeName → tokens with that mode
	var modeOrder []string

	for _, t := range tokens {
		for modeName := range t.Modes {
			if _, exists := modeTokens[modeName]; !exists {
				modeOrder = append(modeOrder, modeName)
			}
			modeTokens[modeName] = append(modeTokens[modeName], t)
		}
	}

	sort.Strings(modeOrder)

	for _, modeName := range modeOrder {
		sb.WriteString(fmt.Sprintf("\n:root[data-color-mode='%s'] {\n", modeName))

		mTokens := modeTokens[modeName]
		sort.Slice(mTokens, func(i, j int) bool {
			return mTokens[i].Name < mTokens[j].Name
		})

		for _, t := range mTokens {
			// Use the original var() reference if available
			value := t.Modes[modeName]
			if raw, exists := t.RawModes[modeName]; exists {
				value = raw
			}
			sb.WriteString(fmt.Sprintf("  %s: %s;\n", t.Name, value))
		}

		sb.WriteString("}\n")
	}

	return sb.String()
}
