package builder

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/artmsilva/cssmark/src/internal/parser"
)

// WriteJS writes the JavaScript, metadata, and declaration artifacts consumed by token clients.
func WriteJS(tokens []parser.Token, jsPath, metaPath, dtsPath string) error {
	ordered := append([]parser.Token(nil), tokens...)
	sort.Slice(ordered, func(i, j int) bool { return programmaticID(ordered[i]) < programmaticID(ordered[j]) })

	values := make(map[string]string, len(ordered))
	modes := make(map[string]map[string]string)
	meta := make(map[string]map[string]any, len(ordered))
	for _, token := range ordered {
		id := programmaticID(token)
		values[id] = token.InitialValue
		if len(token.Modes) > 0 {
			modes[id] = make(map[string]string, len(token.Modes))
			for mode, modeValue := range token.Modes {
				modes[id][mode] = modeValue
			}
		}
		entry := map[string]any{"id": id, "$value": token.InitialValue}
		if token.Type != "" {
			entry["$type"] = token.Type
		}
		if len(modes[id]) > 0 {
			entry["$extensions"] = map[string]any{"mode": modes[id]}
		}
		meta[id] = entry
	}

	valuesJSON, err := json.MarshalIndent(values, "", "  ")
	if err != nil {
		return err
	}
	modesJSON, err := json.MarshalIndent(modes, "", "  ")
	if err != nil {
		return err
	}
	metaJSON, err := json.MarshalIndent(meta, "", "  ")
	if err != nil {
		return err
	}
	js := fmt.Sprintf("/** Autogenerated by cssmark. DO NOT EDIT. */\n\nexport const tokens = %s;\n\nexport const modes = %s;\n\nexport function token(tokenID, modeName) {\n  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];\n  return tokens[tokenID];\n}\n", valuesJSON, modesJSON)
	metaJS := fmt.Sprintf("/** Autogenerated by cssmark. DO NOT EDIT. */\n\nexport const meta = %s;\n", metaJSON)
	dts := "export declare const tokens: Record<string, string>;\nexport declare const modes: Record<string, Record<string, string>>;\nexport declare function token(tokenID: string, modeName?: string): string;\n"
	for path, body := range map[string]string{jsPath: js, metaPath: metaJS, dtsPath: dts} {
		if path == "" {
			continue
		}
		if err := os.WriteFile(path, []byte(body), 0644); err != nil {
			return err
		}
	}
	return nil
}

func programmaticID(token parser.Token) string {
	if token.ID != "" {
		return token.ID
	}
	return strings.TrimPrefix(token.Name, "--")
}
