package dtcg

import (
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// CSSSource emits a deterministic cssmark source file. Composite DTCG values use
// value-json/mode-json descriptors because CSS has no native object literal; the
// descriptors retain lossless source data for a later CSS emission pass.
func CSSSource(tokens []Token) (string, error) {
	var out strings.Builder
	out.WriteString("/* Generated by cssmark dtcg. Edit only after the DTCG cutover. */\n\n")
	for _, token := range tokens {
		out.WriteString(fmt.Sprintf("@property %s {\n", token.Name))
		out.WriteString(fmt.Sprintf("  id: \"%s\";\n", token.ID))
		if token.Type != "" {
			out.WriteString(fmt.Sprintf("  type: \"%s\";\n", token.Type))
		}
		if scalar, ok := token.Value.(string); ok {
			out.WriteString("  syntax: \"*\";\n  inherits: true;\n")
			out.WriteString(fmt.Sprintf("  initial-value: %s;\n", cssValue(scalar)))
		} else {
			encoded, err := json.Marshal(token.Value)
			if err != nil {
				return "", err
			}
			out.WriteString(fmt.Sprintf("  value-json: '%s';\n", strings.ReplaceAll(string(encoded), "'", "\\'")))
		}
		modes := make([]string, 0, len(token.Modes))
		for mode := range token.Modes {
			modes = append(modes, mode)
		}
		sort.Strings(modes)
		for _, mode := range modes {
			if scalar, ok := token.Modes[mode].(string); ok {
				out.WriteString(fmt.Sprintf("  mode-%s: %s;\n", mode, cssValue(scalar)))
			} else {
				encoded, err := json.Marshal(token.Modes[mode])
				if err != nil {
					return "", err
				}
				out.WriteString(fmt.Sprintf("  mode-json-%s: '%s';\n", mode, strings.ReplaceAll(string(encoded), "'", "\\'")))
			}
		}
		out.WriteString("}\n\n")
	}
	return out.String(), nil
}

var alias = regexp.MustCompile(`\{([^}]+)\}`)

func cssValue(value string) string {
	return alias.ReplaceAllStringFunc(value, func(match string) string {
		id := strings.TrimSuffix(strings.TrimPrefix(match, "{"), "}")
		return "var(--hb-" + strings.ReplaceAll(id, ".", "-") + ")"
	})
}
